# Generated by Django 5.0.1 on 2024-01-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Heart_Rate_BPM', models.IntegerField()),
                ('Pulse', models.IntegerField()),
                ('SPO2', models.IntegerField()),
                ('BP_Systolic', models.IntegerField()),
                ('BP_Diastolic', models.IntegerField()),
                ('Skin_Temperature', models.IntegerField()),
                ('Step_Counter', models.IntegerField()),
            ],
        ),
    ]
